name: Build and Push Docker Image to Docker Image Registry

on:
    push:
      branches: 
        - "main"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to CM ecloud registry
        uses: docker/login-action@v2
        with:
          registry: cis-hub-huadong-4.cmecloud.cn
          username: ${{ secrets.CMECLOUD_USERNAME }}
          password: ${{ secrets.CMECLOUD_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ssz66666/docker-smokeping-master-slave:latest
            cis-hub-huadong-4.cmecloud.cn/cmi-product/smokeping-master-slave:v1